//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoaApp.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoaApp.Core.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There were problems during authentication.
        /// </summary>
        internal static string AuthenticationException {
            get {
                return ResourceManager.GetString("AuthenticationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [All users and groups].
        /// </summary>
        internal static string CoaGroup_AllUserName {
            get {
                return ResourceManager.GetString("CoaGroup_AllUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group collection is read only.
        /// </summary>
        internal static string CoaGroupCollectionReadonlyException {
            get {
                return ResourceManager.GetString("CoaGroupCollectionReadonlyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Index out of collection range.
        /// </summary>
        internal static string CoaIndexOutOfRangeException {
            get {
                return ResourceManager.GetString("CoaIndexOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Index out of [{0}] collection range.
        /// </summary>
        internal static string CoaIndexOutOfRangeException_CollectionType {
            get {
                return ResourceManager.GetString("CoaIndexOutOfRangeException_CollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object not belong to collection.
        /// </summary>
        internal static string CoaObjectNotBelontToCollectionException {
            get {
                return ResourceManager.GetString("CoaObjectNotBelontToCollectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object id={0} not found.
        /// </summary>
        internal static string CoaObjectNotFoundException {
            get {
                return ResourceManager.GetString("CoaObjectNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are problem or error on form detected.
        /// </summary>
        internal static string CoaProblemOnFormException {
            get {
                return ResourceManager.GetString("CoaProblemOnFormException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application user collection is read only.
        /// </summary>
        internal static string CoaUserCollectionReadonlyException {
            get {
                return ResourceManager.GetString("CoaUserCollectionReadonlyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For the specified authentication type, you must set a login.
        /// </summary>
        internal static string CoaUserLoginRequiredException {
            get {
                return ResourceManager.GetString("CoaUserLoginRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password must be set for specified authentication type.
        /// </summary>
        internal static string CoaUserPasswordRequiredException {
            get {
                return ResourceManager.GetString("CoaUserPasswordRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to set form script because it contains errors.
        /// </summary>
        internal static string FormSetScriptExceptionStr {
            get {
                return ResourceManager.GetString("FormSetScriptExceptionStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to set object for folder not synchronized with application groups.
        /// </summary>
        internal static string GroupFolderSyncException {
            get {
                return ResourceManager.GetString("GroupFolderSyncException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no object for syncronization with Group.
        /// </summary>
        internal static string GroupSyncRequestException {
            get {
                return ResourceManager.GetString("GroupSyncRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status missing on server, update field edit control.
        /// </summary>
        internal static string MissingStatusOnServerException {
            get {
                return ResourceManager.GetString("MissingStatusOnServerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removing user not belong to user collection.
        /// </summary>
        internal static string RemovingUserNotInCollectionExceptionStr {
            get {
                return ResourceManager.GetString("RemovingUserNotInCollectionExceptionStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link rule check failed.
        /// </summary>
        internal static string RestrictionRuleFailedException {
            get {
                return ResourceManager.GetString("RestrictionRuleFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to set field value [{0}].
        /// </summary>
        internal static string RestrictionRuleFailedException_ForField {
            get {
                return ResourceManager.GetString("RestrictionRuleFailedException_ForField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на During scheme history writing must declare old and new values.
        /// </summary>
        internal static string SchemaHistoryArgumentException {
            get {
                return ResourceManager.GetString("SchemaHistoryArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на During scheme history writing was null argument wigh name &apos;{0}&apos;.
        /// </summary>
        internal static string SchemaHistoryArgumentExceptionWithArgName {
            get {
                return ResourceManager.GetString("SchemaHistoryArgumentExceptionWithArgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scheme not found in database.
        /// </summary>
        internal static string SchemeNotFoundException {
            get {
                return ResourceManager.GetString("SchemeNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The group cannot be updated because the linked object does not support updates.
        /// </summary>
        internal static string SerializationMessageException {
            get {
                return ResourceManager.GetString("SerializationMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server not found on host [{0}] and port [{1}].
        /// </summary>
        internal static string ServerNotFoundException {
            get {
                return ResourceManager.GetString("ServerNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server not found.
        /// </summary>
        internal static string ServerNotFoundExceptionNoInfo {
            get {
                return ResourceManager.GetString("ServerNotFoundExceptionNoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to set null as workflow field value.
        /// </summary>
        internal static string WorkflowNullValueException {
            get {
                return ResourceManager.GetString("WorkflowNullValueException", resourceCulture);
            }
        }
    }
}
