//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoaApp.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoaApp.Core.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There were problems during authentication.
        /// </summary>
        internal static string AuthenticationException {
            get {
                return ResourceManager.GetString("AuthenticationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (All groups).
        /// </summary>
        internal static string BaseGroupDisplayName {
            get {
                return ResourceManager.GetString("BaseGroupDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [All users and groups].
        /// </summary>
        internal static string CoaGroup_AllUserName {
            get {
                return ResourceManager.GetString("CoaGroup_AllUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group collection is read only.
        /// </summary>
        internal static string CoaGroupCollectionReadonlyException {
            get {
                return ResourceManager.GetString("CoaGroupCollectionReadonlyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modification of  application access group was not permitted.
        /// </summary>
        internal static string CoaGroupModificationException {
            get {
                return ResourceManager.GetString("CoaGroupModificationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Index out of collection range.
        /// </summary>
        internal static string CoaIndexOutOfRangeException {
            get {
                return ResourceManager.GetString("CoaIndexOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Index out of [{0}] collection range.
        /// </summary>
        internal static string CoaIndexOutOfRangeException_CollectionType {
            get {
                return ResourceManager.GetString("CoaIndexOutOfRangeException_CollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object not belong to collection.
        /// </summary>
        internal static string CoaObjectNotBelontToCollectionException {
            get {
                return ResourceManager.GetString("CoaObjectNotBelontToCollectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object id={0} not found.
        /// </summary>
        internal static string CoaObjectNotFoundException {
            get {
                return ResourceManager.GetString("CoaObjectNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are problem or error on form detected.
        /// </summary>
        internal static string CoaProblemOnFormException {
            get {
                return ResourceManager.GetString("CoaProblemOnFormException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AND.
        /// </summary>
        internal static string CoaRuleCombinationTermsAnd {
            get {
                return ResourceManager.GetString("CoaRuleCombinationTermsAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OR.
        /// </summary>
        internal static string CoaRuleCombinationTermsOr {
            get {
                return ResourceManager.GetString("CoaRuleCombinationTermsOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на belongs to group.
        /// </summary>
        internal static string CoaRuleComparisonsTypesBelongsToGroup {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesBelongsToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на contains.
        /// </summary>
        internal static string CoaRuleComparisonsTypesContains {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на contains current user.
        /// </summary>
        internal static string CoaRuleComparisonsTypesContainsCurrentUser {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesContainsCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на contains user.
        /// </summary>
        internal static string CoaRuleComparisonsTypesContainsUser {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesContainsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not belongs to group.
        /// </summary>
        internal static string CoaRuleComparisonsTypesDoesNotBelongToGroup {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesDoesNotBelongToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not contain current user.
        /// </summary>
        internal static string CoaRuleComparisonsTypesDoesNotContainCurrentUser {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesDoesNotContainCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not match.
        /// </summary>
        internal static string CoaRuleComparisonsTypesDoesNotMatch {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на =.
        /// </summary>
        internal static string CoaRuleComparisonsTypesEqualTo {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;.
        /// </summary>
        internal static string CoaRuleComparisonsTypesGreaterThan {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на high than.
        /// </summary>
        internal static string CoaRuleComparisonsTypesGreaterThanDropDownText {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesGreaterThanDropDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;=.
        /// </summary>
        internal static string CoaRuleComparisonsTypesGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на high than from.
        /// </summary>
        internal static string CoaRuleComparisonsTypesGreaterThanOrEqualDropDownText {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesGreaterThanOrEqualDropDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is.
        /// </summary>
        internal static string CoaRuleComparisonsTypesIs {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is API interface.
        /// </summary>
        internal static string CoaRuleComparisonsTypesIsApiInterface {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesIsApiInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is background process.
        /// </summary>
        internal static string CoaRuleComparisonsTypesIsBackgroundProcess {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesIsBackgroundProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is group.
        /// </summary>
        internal static string CoaRuleComparisonsTypesIsGroup {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesIsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is initial state.
        /// </summary>
        internal static string CoaRuleComparisonsTypesIsInitialState {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesIsInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is internal user.
        /// </summary>
        internal static string CoaRuleComparisonsTypesIsInternalUser {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesIsInternalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is not.
        /// </summary>
        internal static string CoaRuleComparisonsTypesIsNot {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesIsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is not initial state.
        /// </summary>
        internal static string CoaRuleComparisonsTypesIsNotInitialState {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesIsNotInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is not internal user.
        /// </summary>
        internal static string CoaRuleComparisonsTypesIsNotInternalUser {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesIsNotInternalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is not member.
        /// </summary>
        internal static string CoaRuleComparisonsTypesIsNotMemberOf {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesIsNotMemberOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is superuser.
        /// </summary>
        internal static string CoaRuleComparisonsTypesIsSuperuser {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesIsSuperuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is user.
        /// </summary>
        internal static string CoaRuleComparisonsTypesIsUser {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesIsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is user client.
        /// </summary>
        internal static string CoaRuleComparisonsTypesIsUserClient {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesIsUserClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is visible for current user.
        /// </summary>
        internal static string CoaRuleComparisonsTypesIsVisibleForCurrentUser {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesIsVisibleForCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;.
        /// </summary>
        internal static string CoaRuleComparisonsTypesLessThan {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на lower.
        /// </summary>
        internal static string CoaRuleComparisonsTypesLessThanDropDownText {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesLessThanDropDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;=.
        /// </summary>
        internal static string CoaRuleComparisonsTypesLessThanOrEqual {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesLessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на lower from.
        /// </summary>
        internal static string CoaRuleComparisonsTypesLessThanOrEqualDropDownText {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesLessThanOrEqualDropDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на matches.
        /// </summary>
        internal static string CoaRuleComparisonsTypesMatches {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not contains.
        /// </summary>
        internal static string CoaRuleComparisonsTypesNotContains {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesNotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not contains user.
        /// </summary>
        internal static string CoaRuleComparisonsTypesNotContainsUser {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesNotContainsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !=.
        /// </summary>
        internal static string CoaRuleComparisonsTypesNotEqualTo {
            get {
                return ResourceManager.GetString("CoaRuleComparisonsTypesNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application user collection is read only.
        /// </summary>
        internal static string CoaUserCollectionReadonlyException {
            get {
                return ResourceManager.GetString("CoaUserCollectionReadonlyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot set object from another folder as value.
        /// </summary>
        internal static string CoaUserFieldAnotherFolderException {
            get {
                return ResourceManager.GetString("CoaUserFieldAnotherFolderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid data type for field of type ObjectList.
        /// </summary>
        internal static string CoaUserFieldArgumentObjListTypeException {
            get {
                return ResourceManager.GetString("CoaUserFieldArgumentObjListTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred while setting or getting value.
        /// </summary>
        internal static string CoaUserFieldException {
            get {
                return ResourceManager.GetString("CoaUserFieldException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t install someone else&apos;s collection.
        /// </summary>
        internal static string CoaUserFieldForeignCollectionException {
            get {
                return ResourceManager.GetString("CoaUserFieldForeignCollectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrectly initialized call to [SetObjectListValue].
        /// </summary>
        internal static string CoaUserFieldIncorrectInitializationException {
            get {
                return ResourceManager.GetString("CoaUserFieldIncorrectInitializationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It is not possible to set a value other than the initial state until the object is created.
        /// </summary>
        internal static string CoaUserFieldInitializationValueException {
            get {
                return ResourceManager.GetString("CoaUserFieldInitializationValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The field &quot;{0}&quot; is greater than the allowed length in {1} characters.
        /// </summary>
        internal static string CoaUserFieldValidationGreaterThenErrorMessage {
            get {
                return ResourceManager.GetString("CoaUserFieldValidationGreaterThenErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The field &quot;{0}&quot; less than minimum length ({1}).
        /// </summary>
        internal static string CoaUserFieldValidationLessThenErrorMessage {
            get {
                return ResourceManager.GetString("CoaUserFieldValidationLessThenErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For the specified authentication type, you must set a login.
        /// </summary>
        internal static string CoaUserLoginRequiredException {
            get {
                return ResourceManager.GetString("CoaUserLoginRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password must be set for specified authentication type.
        /// </summary>
        internal static string CoaUserPasswordRequiredException {
            get {
                return ResourceManager.GetString("CoaUserPasswordRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to set form script because it contains errors.
        /// </summary>
        internal static string FormSetScriptExceptionStr {
            get {
                return ResourceManager.GetString("FormSetScriptExceptionStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to set object for folder not synchronized with application groups.
        /// </summary>
        internal static string GroupFolderSyncException {
            get {
                return ResourceManager.GetString("GroupFolderSyncException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group id={0}.
        /// </summary>
        internal static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no object for syncronization with Group.
        /// </summary>
        internal static string GroupSyncRequestException {
            get {
                return ResourceManager.GetString("GroupSyncRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status missing on server, update field edit control.
        /// </summary>
        internal static string MissingStatusOnServerException {
            get {
                return ResourceManager.GetString("MissingStatusOnServerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removing user not belong to user collection.
        /// </summary>
        internal static string RemovingUserNotInCollectionExceptionStr {
            get {
                return ResourceManager.GetString("RemovingUserNotInCollectionExceptionStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link rule check failed.
        /// </summary>
        internal static string RestrictionRuleFailedException {
            get {
                return ResourceManager.GetString("RestrictionRuleFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to set field value [{0}].
        /// </summary>
        internal static string RestrictionRuleFailedException_ForField {
            get {
                return ResourceManager.GetString("RestrictionRuleFailedException_ForField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на During scheme history writing must declare old and new values.
        /// </summary>
        internal static string SchemaHistoryArgumentException {
            get {
                return ResourceManager.GetString("SchemaHistoryArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на During scheme history writing was null argument wigh name &apos;{0}&apos;.
        /// </summary>
        internal static string SchemaHistoryArgumentExceptionWithArgName {
            get {
                return ResourceManager.GetString("SchemaHistoryArgumentExceptionWithArgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scheme not found in database.
        /// </summary>
        internal static string SchemeNotFoundException {
            get {
                return ResourceManager.GetString("SchemeNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The group cannot be updated because the linked object does not support updates.
        /// </summary>
        internal static string SerializationMessageException {
            get {
                return ResourceManager.GetString("SerializationMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server not found on host [{0}] and port [{1}].
        /// </summary>
        internal static string ServerNotFoundException {
            get {
                return ResourceManager.GetString("ServerNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server not found.
        /// </summary>
        internal static string ServerNotFoundExceptionNoInfo {
            get {
                return ResourceManager.GetString("ServerNotFoundExceptionNoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no object for syncronization with User.
        /// </summary>
        internal static string UserSyncRequestException {
            get {
                return ResourceManager.GetString("UserSyncRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to set null as workflow field value.
        /// </summary>
        internal static string WorkflowNullValueException {
            get {
                return ResourceManager.GetString("WorkflowNullValueException", resourceCulture);
            }
        }
    }
}
