//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiObject.AppClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlexiObject.AppClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AboutAppViewAppDescriptionTextBlock {
            get {
                return ResourceManager.GetString("AboutAppViewAppDescriptionTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application title.
        /// </summary>
        public static string AboutAppViewAppTitleTextBlock {
            get {
                return ResourceManager.GetString("AboutAppViewAppTitleTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string AboutAppViewAppVersionTextBlock {
            get {
                return ResourceManager.GetString("AboutAppViewAppVersionTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation system.
        /// </summary>
        public static string AboutAppViewCurrentPlatformTextBlock {
            get {
                return ResourceManager.GetString("AboutAppViewCurrentPlatformTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using components.
        /// </summary>
        public static string AboutAppViewUsingComponentsTextBlock {
            get {
                return ResourceManager.GetString("AboutAppViewUsingComponentsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexible object application.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonCloseText {
            get {
                return ResourceManager.GetString("ButtonCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in application.
        /// </summary>
        public static string DialogMessageErrorCaption {
            get {
                return ResourceManager.GetString("DialogMessageErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string DialogMessageInformationCaption {
            get {
                return ResourceManager.GetString("DialogMessageInformationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string DialogMessageQuestionCaption {
            get {
                return ResourceManager.GetString("DialogMessageQuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string DialogMessageWarningCaption {
            get {
                return ResourceManager.GetString("DialogMessageWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DialogWindowCancel {
            get {
                return ResourceManager.GetString("DialogWindowCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DialogWindowClose {
            get {
                return ResourceManager.GetString("DialogWindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string DialogWindowOkay {
            get {
                return ResourceManager.GetString("DialogWindowOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainVisual.
        /// </summary>
        public static string MainVisual {
            get {
                return ResourceManager.GetString("MainVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MenuItemEdit {
            get {
                return ResourceManager.GetString("MenuItemEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add object.
        /// </summary>
        public static string MenuItemEditAdd {
            get {
                return ResourceManager.GetString("MenuItemEditAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder.
        /// </summary>
        public static string MenuItemEditAddFolder {
            get {
                return ResourceManager.GetString("MenuItemEditAddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolder.
        /// </summary>
        public static string MenuItemEditAddFolderFolder {
            get {
                return ResourceManager.GetString("MenuItemEditAddFolderFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same leverl.
        /// </summary>
        public static string MenuItemEditAddFolderFolderSameLevel {
            get {
                return ResourceManager.GetString("MenuItemEditAddFolderFolderSameLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit object.
        /// </summary>
        public static string MenuItemEditEdit {
            get {
                return ResourceManager.GetString("MenuItemEditEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit folder.
        /// </summary>
        public static string MenuItemEditEditFolder {
            get {
                return ResourceManager.GetString("MenuItemEditEditFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string MenuItemEditRefresh {
            get {
                return ResourceManager.GetString("MenuItemEditRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete object.
        /// </summary>
        public static string MenuItemEditRemove {
            get {
                return ResourceManager.GetString("MenuItemEditRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folder.
        /// </summary>
        public static string MenuItemEditRemoveFolder {
            get {
                return ResourceManager.GetString("MenuItemEditRemoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuItemFile {
            get {
                return ResourceManager.GetString("MenuItemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administring.
        /// </summary>
        public static string MenuItemFileAdmin {
            get {
                return ResourceManager.GetString("MenuItemFileAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active sessions.
        /// </summary>
        public static string MenuItemFileAdminActiveSessions {
            get {
                return ResourceManager.GetString("MenuItemFileAdminActiveSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked objects.
        /// </summary>
        public static string MenuItemFileAdminBlockedObjects {
            get {
                return ResourceManager.GetString("MenuItemFileAdminBlockedObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client parameters.
        /// </summary>
        public static string MenuItemFileAdminClientParameters {
            get {
                return ResourceManager.GetString("MenuItemFileAdminClientParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coloring schema.
        /// </summary>
        public static string MenuItemFileAdminColorSchema {
            get {
                return ResourceManager.GetString("MenuItemFileAdminColorSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all client objects.
        /// </summary>
        public static string MenuItemFileAdminDeleteAllObjects {
            get {
                return ResourceManager.GetString("MenuItemFileAdminDeleteAllObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion log.
        /// </summary>
        public static string MenuItemFileAdminDeletionLog {
            get {
                return ResourceManager.GetString("MenuItemFileAdminDeletionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global forms.
        /// </summary>
        public static string MenuItemFileAdminGlobalForms {
            get {
                return ResourceManager.GetString("MenuItemFileAdminGlobalForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image collection.
        /// </summary>
        public static string MenuItemFileAdminImageCollection {
            get {
                return ResourceManager.GetString("MenuItemFileAdminImageCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled tasks.
        /// </summary>
        public static string MenuItemFileAdminScheduledTasks {
            get {
                return ResourceManager.GetString("MenuItemFileAdminScheduledTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema history.
        /// </summary>
        public static string MenuItemFileAdminSchemaHistory {
            get {
                return ResourceManager.GetString("MenuItemFileAdminSchemaHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System parameters.
        /// </summary>
        public static string MenuItemFileAdminSystemParameters {
            get {
                return ResourceManager.GetString("MenuItemFileAdminSystemParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuItemFileExit {
            get {
                return ResourceManager.GetString("MenuItemFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit and enter.
        /// </summary>
        public static string MenuItemFileExitAndEnter {
            get {
                return ResourceManager.GetString("MenuItemFileExitAndEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify user.
        /// </summary>
        public static string MenuItemFileNotifyUser {
            get {
                return ResourceManager.GetString("MenuItemFileNotifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string MenuItemFilePrint {
            get {
                return ResourceManager.GetString("MenuItemFilePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent objects.
        /// </summary>
        public static string MenuItemFileRecentObjects {
            get {
                return ResourceManager.GetString("MenuItemFileRecentObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global scenarios.
        /// </summary>
        public static string MenuItemFileSciptsGlobal {
            get {
                return ResourceManager.GetString("MenuItemFileSciptsGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios.
        /// </summary>
        public static string MenuItemFileScripts {
            get {
                return ResourceManager.GetString("MenuItemFileScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string MenuItemFileScriptsSearch {
            get {
                return ResourceManager.GetString("MenuItemFileScriptsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string MenuItemFileScriptsState {
            get {
                return ResourceManager.GetString("MenuItemFileScriptsState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuItemHelp {
            get {
                return ResourceManager.GetString("MenuItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuItemHelpAbout {
            get {
                return ResourceManager.GetString("MenuItemHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuItemHelpHelp {
            get {
                return ResourceManager.GetString("MenuItemHelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruments.
        /// </summary>
        public static string MenuItemInstruments {
            get {
                return ResourceManager.GetString("MenuItemInstruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open object by id.
        /// </summary>
        public static string MenuItemInstrumentsOpenObjectById {
            get {
                return ResourceManager.GetString("MenuItemInstrumentsOpenObjectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open scenario editor.
        /// </summary>
        public static string MenuItemInstrumentsOpenScenarioEditor {
            get {
                return ResourceManager.GetString("MenuItemInstrumentsOpenScenarioEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuItemInstrumentsSettings {
            get {
                return ResourceManager.GetString("MenuItemInstrumentsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuItemSettings {
            get {
                return ResourceManager.GetString("MenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        public static string MenuItemSettingsApp {
            get {
                return ResourceManager.GetString("MenuItemSettingsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open setup folder.
        /// </summary>
        public static string MenuItemSettingsOpenSetupFolder {
            get {
                return ResourceManager.GetString("MenuItemSettingsOpenSetupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MenuItemView {
            get {
                return ResourceManager.GetString("MenuItemView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument panels.
        /// </summary>
        public static string MenuItemViewInstrumentPanels {
            get {
                return ResourceManager.GetString("MenuItemViewInstrumentPanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User notifies.
        /// </summary>
        public static string MenuItemViewNotifies {
            get {
                return ResourceManager.GetString("MenuItemViewNotifies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder tree.
        /// </summary>
        public static string MenuItemViewTreeFolder {
            get {
                return ResourceManager.GetString("MenuItemViewTreeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working with folder.
        /// </summary>
        public static string MenuItemViewWorkWithFolder {
            get {
                return ResourceManager.GetString("MenuItemViewWorkWithFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working with object.
        /// </summary>
        public static string MenuItemViewWorkWithObject {
            get {
                return ResourceManager.GetString("MenuItemViewWorkWithObject", resourceCulture);
            }
        }
    }
}
