//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom object application.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string ButtonCloseText {
            get {
                return ResourceManager.GetString("ButtonCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string DialogWindowCancel {
            get {
                return ResourceManager.GetString("DialogWindowCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string DialogWindowClose {
            get {
                return ResourceManager.GetString("DialogWindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string DialogWindowOkay {
            get {
                return ResourceManager.GetString("DialogWindowOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Avalon Edit.
        /// </summary>
        public static string License_AvalonEdit {
            get {
                return ResourceManager.GetString("License_AvalonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom object application.
        /// </summary>
        public static string License_CustomObjectApplication {
            get {
                return ResourceManager.GetString("License_CustomObjectApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extended.Wpf.Toolkit.
        /// </summary>
        public static string License_ExtendedWpfToolkit {
            get {
                return ResourceManager.GetString("License_ExtendedWpfToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LinqToExcel.
        /// </summary>
        public static string License_LinqToExcel {
            get {
                return ResourceManager.GetString("License_LinqToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WPF extended controls.
        /// </summary>
        public static string License_WpfExtendedControls {
            get {
                return ResourceManager.GetString("License_WpfExtendedControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MainVisual.
        /// </summary>
        public static string MainVisual {
            get {
                return ResourceManager.GetString("MainVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string MenuItemEdit {
            get {
                return ResourceManager.GetString("MenuItemEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add object.
        /// </summary>
        public static string MenuItemEditAdd {
            get {
                return ResourceManager.GetString("MenuItemEditAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add folder.
        /// </summary>
        public static string MenuItemEditAddFolder {
            get {
                return ResourceManager.GetString("MenuItemEditAddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subfolder.
        /// </summary>
        public static string MenuItemEditAddFolderFolder {
            get {
                return ResourceManager.GetString("MenuItemEditAddFolderFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Same leverl.
        /// </summary>
        public static string MenuItemEditAddFolderFolderSameLevel {
            get {
                return ResourceManager.GetString("MenuItemEditAddFolderFolderSameLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit object.
        /// </summary>
        public static string MenuItemEditEdit {
            get {
                return ResourceManager.GetString("MenuItemEditEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit folder.
        /// </summary>
        public static string MenuItemEditEditFolder {
            get {
                return ResourceManager.GetString("MenuItemEditEditFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh.
        /// </summary>
        public static string MenuItemEditRefresh {
            get {
                return ResourceManager.GetString("MenuItemEditRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete object.
        /// </summary>
        public static string MenuItemEditRemove {
            get {
                return ResourceManager.GetString("MenuItemEditRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete folder.
        /// </summary>
        public static string MenuItemEditRemoveFolder {
            get {
                return ResourceManager.GetString("MenuItemEditRemoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        public static string MenuItemFile {
            get {
                return ResourceManager.GetString("MenuItemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Administring.
        /// </summary>
        public static string MenuItemFileAdmin {
            get {
                return ResourceManager.GetString("MenuItemFileAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Active sessions.
        /// </summary>
        public static string MenuItemFileAdminActiveSessions {
            get {
                return ResourceManager.GetString("MenuItemFileAdminActiveSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blocked objects.
        /// </summary>
        public static string MenuItemFileAdminBlockedObjects {
            get {
                return ResourceManager.GetString("MenuItemFileAdminBlockedObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Client parameters.
        /// </summary>
        public static string MenuItemFileAdminClientParameters {
            get {
                return ResourceManager.GetString("MenuItemFileAdminClientParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Coloring schema.
        /// </summary>
        public static string MenuItemFileAdminColorSchema {
            get {
                return ResourceManager.GetString("MenuItemFileAdminColorSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete all client objects.
        /// </summary>
        public static string MenuItemFileAdminDeleteAllObjects {
            get {
                return ResourceManager.GetString("MenuItemFileAdminDeleteAllObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deletion log.
        /// </summary>
        public static string MenuItemFileAdminDeletionLog {
            get {
                return ResourceManager.GetString("MenuItemFileAdminDeletionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Global forms.
        /// </summary>
        public static string MenuItemFileAdminGlobalForms {
            get {
                return ResourceManager.GetString("MenuItemFileAdminGlobalForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image collection.
        /// </summary>
        public static string MenuItemFileAdminImageCollection {
            get {
                return ResourceManager.GetString("MenuItemFileAdminImageCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scheduled tasks.
        /// </summary>
        public static string MenuItemFileAdminScheduledTasks {
            get {
                return ResourceManager.GetString("MenuItemFileAdminScheduledTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Schema history.
        /// </summary>
        public static string MenuItemFileAdminSchemaHistory {
            get {
                return ResourceManager.GetString("MenuItemFileAdminSchemaHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System parameters.
        /// </summary>
        public static string MenuItemFileAdminSystemParameters {
            get {
                return ResourceManager.GetString("MenuItemFileAdminSystemParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string MenuItemFileExit {
            get {
                return ResourceManager.GetString("MenuItemFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit and enter.
        /// </summary>
        public static string MenuItemFileExitAndEnter {
            get {
                return ResourceManager.GetString("MenuItemFileExitAndEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notify user.
        /// </summary>
        public static string MenuItemFileNotifyUser {
            get {
                return ResourceManager.GetString("MenuItemFileNotifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print.
        /// </summary>
        public static string MenuItemFilePrint {
            get {
                return ResourceManager.GetString("MenuItemFilePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recent objects.
        /// </summary>
        public static string MenuItemFileRecentObjects {
            get {
                return ResourceManager.GetString("MenuItemFileRecentObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Global scenarios.
        /// </summary>
        public static string MenuItemFileSciptsGlobal {
            get {
                return ResourceManager.GetString("MenuItemFileSciptsGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scenarios.
        /// </summary>
        public static string MenuItemFileScripts {
            get {
                return ResourceManager.GetString("MenuItemFileScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string MenuItemFileScriptsSearch {
            get {
                return ResourceManager.GetString("MenuItemFileScriptsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        public static string MenuItemFileScriptsState {
            get {
                return ResourceManager.GetString("MenuItemFileScriptsState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string MenuItemHelp {
            get {
                return ResourceManager.GetString("MenuItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string MenuItemHelpAbout {
            get {
                return ResourceManager.GetString("MenuItemHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string MenuItemHelpHelp {
            get {
                return ResourceManager.GetString("MenuItemHelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Instruments.
        /// </summary>
        public static string MenuItemInstruments {
            get {
                return ResourceManager.GetString("MenuItemInstruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open object by id.
        /// </summary>
        public static string MenuItemInstrumentsOpenObjectById {
            get {
                return ResourceManager.GetString("MenuItemInstrumentsOpenObjectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open scenario editor.
        /// </summary>
        public static string MenuItemInstrumentsOpenScenarioEditor {
            get {
                return ResourceManager.GetString("MenuItemInstrumentsOpenScenarioEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string MenuItemInstrumentsSettings {
            get {
                return ResourceManager.GetString("MenuItemInstrumentsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string MenuItemSettings {
            get {
                return ResourceManager.GetString("MenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open settings.
        /// </summary>
        public static string MenuItemSettingsApp {
            get {
                return ResourceManager.GetString("MenuItemSettingsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open setup folder.
        /// </summary>
        public static string MenuItemSettingsOpenSetupFolder {
            get {
                return ResourceManager.GetString("MenuItemSettingsOpenSetupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View.
        /// </summary>
        public static string MenuItemView {
            get {
                return ResourceManager.GetString("MenuItemView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Instrument panels.
        /// </summary>
        public static string MenuItemViewInstrumentPanels {
            get {
                return ResourceManager.GetString("MenuItemViewInstrumentPanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User notifies.
        /// </summary>
        public static string MenuItemViewNotifies {
            get {
                return ResourceManager.GetString("MenuItemViewNotifies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder tree.
        /// </summary>
        public static string MenuItemViewTreeFolder {
            get {
                return ResourceManager.GetString("MenuItemViewTreeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Working with folder.
        /// </summary>
        public static string MenuItemViewWorkWithFolder {
            get {
                return ResourceManager.GetString("MenuItemViewWorkWithFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Working with object.
        /// </summary>
        public static string MenuItemViewWorkWithObject {
            get {
                return ResourceManager.GetString("MenuItemViewWorkWithObject", resourceCulture);
            }
        }
    }
}
